### ISSUE TITLE
[1.20.1 Forge] Server crash on startup

### ISSUE THREAD

**Issue by MrKashew** [jahirxtrap/walljump#1]
[crash-2023-09-03_02.36.13-fml.txt](https://github.com/jahirxtrap/walljump/files/12505657/crash-2023-09-03_02.36.13-fml.txt)

**Comment by jahirxtrap** [comment]
The mod was tested on a forge server 1.20.1-47.1.46, if it doesn't work it probably conflicts with another mod, could you give me a list of the mods you are using?  and i'll try to replicate the bug
