### ISSUE TITLE
Multiplayer - Unable to disable reCling

### ISSUE THREAD

**Issue by LordManzana** [jahirxtrap/walljump#10]
Unable to force config from server to users. Whatever I configure at \server\config\walljump.json does not apply to clients. For example, I don't want to let users reCling, but in the config, I can see "allowReClinging": false and users are still able to reCling since the mod loads its own config (Forge 1.20.1). Is there anything that I'm doing wrong?

Server config:
`{
  "allowReClinging": false,
  "autoRotation": false,
  "onFallDoubleJump": false,
  "exhaustionWallJump": 0.8,
  "minFallDistance": 7.5,
  "elytraSpeedBoost": 0.0,
  "sprintSpeedBoost": 0.0,
  "stepAssist": true,
  "useDoubleJump": false,
  "useWallJump": false,
  "wallJumpHeight": 0.55,
  "wallSlideDelay": 15,
  "stopWallSlideDelay": 72000,
  "playFallSound": true,
  "enableEnchantments": true,
  "enableWallJump": true,
  "enableDoubleJump": false,
  "enableSpeedBoost": false
}`

Config load from mod, ignoring server config:
![image](https://github.com/jahirxtrap/walljump/assets/7037610/81d0059e-946c-4192-8de5-2040be190e90)

**Comment by jahirxtrap** [comment]
Server configs still not syncing with client.

**Comment by jahirxtrap** [comment]
#4
