### ISSUE TITLE
(FABRIC) Bug: Minecraft crashes while trying to join a realm with Wall-Jump Enchantments enabled

### ISSUE THREAD

**Issue by anonymousreindeer** [jahirxtrap/walljump#12]
Self-explanatory title. Whenever I try to join a realm, the game simply crashes and I get this error code. 

![image_2024-06-17_125455884](https://github.com/jahirxtrap/walljump/assets/173085969/6326f9c5-3ce2-46e9-8d38-a20ec80c393d)

Not sure if this is intentional or not. It doesn't happen with multiplayer servers, only realms. Also not sure if this happens with the Forge or Neoforge versions, as I have only tested it with Fabric.

**Comment by jahirxtrap** [comment]
It's an issue with Minecraft Realms. Only client-side mods can be used, but in this case, there's an attempt to modify the server, which is why it crashes.

**Comment by anonymousreindeer** [comment]
If this were the case, then why was I able to use the mod on realms in 1.20.6? I have used the mod on realms for almost a year with no issues until now. Just wondering.

**Comment by anonymousreindeer** [comment]
> It's an issue with Minecraft Realms. Only client-side mods can be used, but in this case, there's an attempt to modify the server, which is why it crashes.

If this were the case, then why was I able to use the mod on realms in 1.20.6? I have used the mod on realms for almost a year with no issues until now. Just wondering.

**Comment by jahirxtrap** [comment]
#15
