### ISSUE TITLE
Enchantments Apply to all armor, even incompatible ones

### ISSUE THREAD

**Issue by Jack-Chronicle** [jahirxtrap/walljump#14]
The enchantments will apply to any piece of armor, even when they don't give an effect when wearing the enchanted piece

**Comment by jahirxtrap** [comment]
Fixed un 1.2.0

**Comment by Jack-Chronicle** [comment]
Will this update be coming to 1.20.4 as well?

**Comment by jahirxtrap** [comment]
Probably yes, it seems that many people are still using that version.
