### ISSUE TITLE
Wall cling, wall jump, double jump do not work without enchantments enabled. (Fabric) [1.21]

### ISSUE THREAD

**Issue by Drajean** [jahirxtrap/walljump#15]
Wall cling, wall jump, double jump do not work without enchantments enabled. Sprint speed increase does however work. I mostly play on a  "vanilla" realm server, and after the update to 1.21 it stopped working. Not that it has relevance but I have spoken to the admin of the server and they are fine with me using it on the server.

 Something about 1.21 changed how realms interacts with the mod, causing crashes which you already know about, the fix being disabling enchants in the mod menu. However that removes the ability to do the aforementioned actions.

 Until the update you released in the last few days none of it worked, now however with enchants off the sprint speed increase does work. I tested it in single player as well, same thing, enchants off: sprint speed works, nothing else does. Enchants on, no gear enchanted: double jump wall cling and wall jump works. 

If more info is needed I will provide ASAP
 
 Thank you for making the mod regardless, makes exploring caves (and friends bases) way more fun.

**Comment by Camawama** [comment]
I think the same thing is happening to me in the latest update. I have enchantments disabled and noticed that walljump is no longer working.

**Comment by jahirxtrap** [comment]
Ok I got it, thanks for explaining the problem in detail.

**Comment by Camawama** [comment]
I should mention that I'm on Forge 1.20.1
