### ISSUE TITLE
1,20,1 is not easy to use

### ISSUE THREAD

**Issue by zc1108aaa** [jahirxtrap/walljump#18]
1.18 Two stage jump can jump up to 3 steps high, multi stage jump
![image](https://github.com/user-attachments/assets/60149c90-f6d9-4064-a132-5acb71294a5c)

1.20.1 Only one jump, affecting my placement of blocks
![image](https://github.com/user-attachments/assets/169542c3-7bf6-4341-a53a-febdea4c5773)

**Comment by zc1108aaa** [comment]
Also, it affects my ability to press and shift down the key

**Comment by jahirxtrap** [comment]
I'm not the author of Wall Jump Unofficial, but you can enable the `"useDoubleJump"` option in the mod config to make it behave similarly.
