### ISSUE TITLE
Step assist doesn't work in 1.21

### ISSUE THREAD

**Issue by SummitSummit** [jahirxtrap/walljump#19]
Just downloaded the Direwolf20 pack for MC1.21 and added this mod because I love clinging to walls.  This mod also says it includes step assist (so I don't have to find a separate mod for that) and it says it is enabled in the config, but it doesn't work.

**Comment by jahirxtrap** [comment]
Step Assist in this mod allows you to jump 1.5 blocks and jump over fences.
