### ISSUE TITLE
Double Jump Doesn't Work as Enchantment

### ISSUE THREAD

**Issue by Xavyrr** [jahirxtrap/walljump#20]
Hello,

It seems that the double jump features does not work when you limit it to enchanted armor:
Config JSON snippet:
`{
  ...
  "useDoubleJump": false,
  ...
  "enableEnchantments": true,
  "enableDoubleJump": true,
  ...
}`

It works fine if it's always enabled using `"useDoubleJump": true,` 

Steps to reproduce:
1. Set config per the above snippet.
2. Enchant item with Double Jump I or Double Jump II
3. Try to double jump

Mod Loader: Fabric 0.16.3
Minecraft: 1.21
Mod Version: 1.2.4

As a side note, when using `"useDoubleJump": true` the enchantment doesn't change anything, but that may be unrelated.

**Comment by jahirxtrap** [comment]
I checked it, and everything is working fine. The enchantment only works when it's applied to boots and equipped in the boots slot. Are you using any other mods alongside this one?
