### ISSUE TITLE
Wall-Jump TXF 1.20.1-1.2.5-forge fails to load on Mac

### ISSUE THREAD

**Issue by Naxum** [jahirxtrap/walljump#21]
I tried both latest NeoForge & Forge mod loaders for Minecraft 1.20.1, and both stop on the red Mojang loading screen when using Wall Jump TXF 1.2.5, downgrading to 1.2.1 resolves the issue. There is no obvious information to me in the logs, I had to hunt down this specific mod causing the issue, womp womp.

<img width="966" alt="Screenshot 2024-10-01 at 2 22 08 PM" src="https://github.com/user-attachments/assets/d5341374-cd6e-419b-b25d-bbed3395bf69">
The loader has stopped here, it no longer updates. It does not "freeze" or "crash" in the traditional sense, just simply stops proceeding or drawing anything.

This problem happens when the mod is present either by itself or with any other mods. Below logs are with solely this mod installed, no others.

[debug.log](https://github.com/user-attachments/files/17216622/debug.log)
[latest.log](https://github.com/user-attachments/files/17216623/latest.log)

**Comment by jahirxtrap** [comment]
This is a known issue, I'll fix it soon :)

**Comment by jahirxtrap** [comment]
Please check if everything works fine in 1.2.6
