### ISSUE TITLE
Add falling sound

### ISSUE THREAD

**Issue by Kichura** [jahirxtrap/walljump#24]
When the player begins to fall from a small/medium/large height, the elytra sound should play and then stop once player lands on the block. This feature was a thing in [genandnic's wall jump mod](https://www.curseforge.com/minecraft/mc-mods/wall-jump) but is not featured here.

**Comment by jahirxtrap** [comment]
That feature was temporarily removed, it will eventually be re-implemented

**Comment by Kichura** [comment]
Just checked the source code and yeah, that's a bit of a shame but hopefully it can one day return for another day.

**Comment by jahirxtrap** [comment]
Added in 1.2.8
