### ISSUE TITLE
Mid-air pause and window switch creates speed boost (singleplayer)

### ISSUE THREAD

**Issue by Bitewack** [jahirxtrap/walljump#5]
Video demonstration:
https://github.com/jahirxtrap/walljump/assets/131537305/1a8dee7e-8b75-4c74-b67e-a6c6d9f010d3

My mod config if needed:
![image](https://github.com/jahirxtrap/walljump/assets/131537305/0faa8c31-7e4f-4ff2-ab6f-d3331f145e3e)

No movement mods installed aside walljump

**Comment by makumaku1974** [comment]
This is still currently occurring on my gameplay too. Still hasn't been fix till now 2024.
