### ISSUE TITLE
[Suggestion] Config option to not reset FallHeight on Doublejump

### ISSUE THREAD

**Issue by Crankonator** [jahirxtrap/walljump#6]
As the title says.
We are wanting to include your mod in our modpack, however being able to mitigate a 200 block fall just like that is kinda OP, so it would be nice to have an option to turn that off :))

**Comment by Crankonator** [comment]
A team member of mine suggests Subtracting the jump height from the fall distance as an option

**Comment by jahirxtrap** [comment]
Added an option to prevent the player from performing a double jump when they have a certain fall speed (which is reached after falling more than 3 blocks)
